resources:
  - name: cf-watch
    type: git
    source:
      uri: https://github.com/pivotal-cf/cf-watch.git
      branch: wip-nanocf

jobs:
  - name: unit-tests
    plan:
    - get: cf-watch
      trigger: true
    - task: unit-tests
      file: cf-watch/ci/tasks/unit-tests/task.yml

  - name: acceptance-tests
    plan:
    - get: cf-watch
      trigger: true
      passed: [unit-tests]
    - task: acceptance-tests
      file: cf-watch/ci/tasks/acceptance-tests/task.yml
